- key: home
  command: heal
- key: insert
  command: fly
- key: q
  modifiers: build
  command: hammer_shape
  tag: change_shape
- key: wheel
  modifiers: leftshift,build
  command: hammer_zoom 5%
  tag: build_scaling_mouse_wheel
- key: wheel
  modifiers: leftshift,build
  command: hammer_zoom_x_cmd 1
  tag: command_radius_mouse_wheel
- key: wheel
  modifiers: leftshift,leftalt,build
  command: hammer_zoom_z_cmd 1
  tag: command_depth_mouse_wheel
- key: wheel
  modifiers: leftshift,leftcontrol,build
  command: hammer_zoom_y_cmd 0.5
  tag: command_height_mouse_wheel
- key: pageup
  modifiers: build
  command: hammer_move_up 0.1
  tag: move_up
- key: pageup
  modifiers: leftalt,build
  command: hammer_move_up 1
  tag: move_up_large
- key: pagedown
  modifiers: build
  command: hammer_move_down 0.1
  tag: move_down
- key: pagedown
  modifiers: leftalt,build
  command: hammer_move_down 1
  tag: move_down_large
- key: leftarrow
  modifiers: build
  command: hammer_move_left 0.1
  tag: move_left
- key: leftarrow
  modifiers: leftalt,build
  command: hammer_move_left 1
  tag: move_left_large
- key: rightarrow
  modifiers: build
  command: hammer_move_right 0.1
  tag: move_right
- key: rightarrow
  modifiers: leftalt,build
  command: hammer_move_right 1
  tag: move_right_large
- key: uparrow
  modifiers: build
  command: hammer_move_forward 0.1
  tag: move_forward
- key: uparrow
  modifiers: leftalt,build
  command: hammer_move_forward 1
  tag: move_forward_large
- key: downarrow
  modifiers: build
  command: hammer_move_backward 0.1
  tag: move_backward
- key: downarrow
  modifiers: leftalt,build
  command: hammer_move_backward 1
  tag: move_backward_large
- key: keypad0
  modifiers: build
  command: hammer_freeze
  tag: freeze_selection
- key: keypad5
  command: hammer
  tag: select
- key: keypad5
  modifiers: leftcontrol
  command: hammer freeze
  tag: select_frozen
- key: keypad5
  modifiers: leftalt
  command: hammer pick
  tag: pick
- key: keypad5
  modifiers: leftcontrol,leftalt
  command: hammer pick freeze
  tag: pick_frozen
- key: keypad7
  command: hammer_undo
  tag: undo
- key: keypad9
  command: hammer_redo
  tag: redo
